version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: petclinic-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - petclinic-network

  petclinic:
    build: .
    container_name: petclinic-app
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
    restart: always
    networks:
      - petclinic-network

volumes:
  mysql-data:

networks:
  petclinic-network:
    driver: bridge
